//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PatentCaseSystem.Module.BusinessObjects.DBIPS4_PA
{

    public partial class TCstmr_Client : XPLiteObject
    {
        int fn_ClientID;
        [Key(true)]
        public int n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<int>("n_ClientID", ref fn_ClientID, value); }
        }
        string fs_Name;
        [Size(300)]
        public string s_Name
        {
            get { return fs_Name; }
            set { SetPropertyValue<string>("s_Name", ref fs_Name, value); }
        }
        string fs_NativeName;
        [Size(200)]
        public string s_NativeName
        {
            get { return fs_NativeName; }
            set { SetPropertyValue<string>("s_NativeName", ref fs_NativeName, value); }
        }
        string fs_OtherName;
        [Size(200)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_ClientCode;
        [Size(20)]
        public string s_ClientCode
        {
            get { return fs_ClientCode; }
            set { SetPropertyValue<string>("s_ClientCode", ref fs_ClientCode, value); }
        }
        string fs_IPType;
        [Size(50)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        string fs_Type;
        [Size(50)]
        public string s_Type
        {
            get { return fs_Type; }
            set { SetPropertyValue<string>("s_Type", ref fs_Type, value); }
        }
        string fs_Credit;
        [Size(50)]
        public string s_Credit
        {
            get { return fs_Credit; }
            set { SetPropertyValue<string>("s_Credit", ref fs_Credit, value); }
        }
        int fn_ApplicantID;
        public int n_ApplicantID
        {
            get { return fn_ApplicantID; }
            set { SetPropertyValue<int>("n_ApplicantID", ref fn_ApplicantID, value); }
        }
        int fn_CoopAgencyID;
        public int n_CoopAgencyID
        {
            get { return fn_CoopAgencyID; }
            set { SetPropertyValue<int>("n_CoopAgencyID", ref fn_CoopAgencyID, value); }
        }
        int fn_IntroID;
        public int n_IntroID
        {
            get { return fn_IntroID; }
            set { SetPropertyValue<int>("n_IntroID", ref fn_IntroID, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        int fn_Language;
        public int n_Language
        {
            get { return fn_Language; }
            set { SetPropertyValue<int>("n_Language", ref fn_Language, value); }
        }
        DateTime fdt_FirstCaseDate;
        public DateTime dt_FirstCaseDate
        {
            get { return fdt_FirstCaseDate; }
            set { SetPropertyValue<DateTime>("dt_FirstCaseDate", ref fdt_FirstCaseDate, value); }
        }
        DateTime fdt_LastCaseDate;
        public DateTime dt_LastCaseDate
        {
            get { return fdt_LastCaseDate; }
            set { SetPropertyValue<DateTime>("dt_LastCaseDate", ref fdt_LastCaseDate, value); }
        }
        string fs_Phone;
        [Size(150)]
        public string s_Phone
        {
            get { return fs_Phone; }
            set { SetPropertyValue<string>("s_Phone", ref fs_Phone, value); }
        }
        string fs_Mobile;
        [Size(150)]
        public string s_Mobile
        {
            get { return fs_Mobile; }
            set { SetPropertyValue<string>("s_Mobile", ref fs_Mobile, value); }
        }
        string fs_Fax;
        [Size(150)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(300)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_Website;
        [Size(300)]
        public string s_Website
        {
            get { return fs_Website; }
            set { SetPropertyValue<string>("s_Website", ref fs_Website, value); }
        }
        string fs_IMAddress;
        public string s_IMAddress
        {
            get { return fs_IMAddress; }
            set { SetPropertyValue<string>("s_IMAddress", ref fs_IMAddress, value); }
        }
        string fs_Facebook;
        [Size(200)]
        public string s_Facebook
        {
            get { return fs_Facebook; }
            set { SetPropertyValue<string>("s_Facebook", ref fs_Facebook, value); }
        }
        string fs_Twitter;
        [Size(200)]
        public string s_Twitter
        {
            get { return fs_Twitter; }
            set { SetPropertyValue<string>("s_Twitter", ref fs_Twitter, value); }
        }
        string fs_PayMode;
        [Size(2)]
        public string s_PayMode
        {
            get { return fs_PayMode; }
            set { SetPropertyValue<string>("s_PayMode", ref fs_PayMode, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_IPRole;
        [Size(50)]
        public string s_IPRole
        {
            get { return fs_IPRole; }
            set { SetPropertyValue<string>("s_IPRole", ref fs_IPRole, value); }
        }
        DateTime fdt_FirstCaseDate34;
        public DateTime dt_FirstCaseDate34
        {
            get { return fdt_FirstCaseDate34; }
            set { SetPropertyValue<DateTime>("dt_FirstCaseDate34", ref fdt_FirstCaseDate34, value); }
        }
        string fs_IsActive;
        [Size(1)]
        public string s_IsActive
        {
            get { return fs_IsActive; }
            set { SetPropertyValue<string>("s_IsActive", ref fs_IsActive, value); }
        }
        string fs_IsAllUser;
        [Size(1)]
        public string s_IsAllUser
        {
            get { return fs_IsAllUser; }
            set { SetPropertyValue<string>("s_IsAllUser", ref fs_IsAllUser, value); }
        }
        decimal fn_ClientDeposit;
        public decimal n_ClientDeposit
        {
            get { return fn_ClientDeposit; }
            set { SetPropertyValue<decimal>("n_ClientDeposit", ref fn_ClientDeposit, value); }
        }
        int fn_ClientDepositCurrency;
        public int n_ClientDepositCurrency
        {
            get { return fn_ClientDepositCurrency; }
            set { SetPropertyValue<int>("n_ClientDepositCurrency", ref fn_ClientDepositCurrency, value); }
        }
        string fs_Source;
        public string s_Source
        {
            get { return fs_Source; }
            set { SetPropertyValue<string>("s_Source", ref fs_Source, value); }
        }
        int fn_Country;
        public int n_Country
        {
            get { return fn_Country; }
            set { SetPropertyValue<int>("n_Country", ref fn_Country, value); }
        }
        string fs_State;
        public string s_State
        {
            get { return fs_State; }
            set { SetPropertyValue<string>("s_State", ref fs_State, value); }
        }
        string fs_City;
        public string s_City
        {
            get { return fs_City; }
            set { SetPropertyValue<string>("s_City", ref fs_City, value); }
        }
        string fs_Area;
        public string s_Area
        {
            get { return fs_Area; }
            set { SetPropertyValue<string>("s_Area", ref fs_Area, value); }
        }
        int fn_PatentChargerID;
        public int n_PatentChargerID
        {
            get { return fn_PatentChargerID; }
            set { SetPropertyValue<int>("n_PatentChargerID", ref fn_PatentChargerID, value); }
        }
        int fn_TMChargerID;
        public int n_TMChargerID
        {
            get { return fn_TMChargerID; }
            set { SetPropertyValue<int>("n_TMChargerID", ref fn_TMChargerID, value); }
        }
        string fs_Lock;
        [Size(1)]
        public string s_Lock
        {
            get { return fs_Lock; }
            set { SetPropertyValue<string>("s_Lock", ref fs_Lock, value); }
        }
        string fs_Locker;
        [Size(20)]
        public string s_Locker
        {
            get { return fs_Locker; }
            set { SetPropertyValue<string>("s_Locker", ref fs_Locker, value); }
        }
        decimal fn_ClientDepositTransfer;
        public decimal n_ClientDepositTransfer
        {
            get { return fn_ClientDepositTransfer; }
            set { SetPropertyValue<decimal>("n_ClientDepositTransfer", ref fn_ClientDepositTransfer, value); }
        }
        string fs_Creator;
        [Size(50)]
        public string s_Creator
        {
            get { return fs_Creator; }
            set { SetPropertyValue<string>("s_Creator", ref fs_Creator, value); }
        }
        string fs_Editor;
        [Size(50)]
        public string s_Editor
        {
            get { return fs_Editor; }
            set { SetPropertyValue<string>("s_Editor", ref fs_Editor, value); }
        }
        string fs_DepositEditor;
        [Size(50)]
        public string s_DepositEditor
        {
            get { return fs_DepositEditor; }
            set { SetPropertyValue<string>("s_DepositEditor", ref fs_DepositEditor, value); }
        }
        DateTime fdt_DepositEditDate;
        public DateTime dt_DepositEditDate
        {
            get { return fdt_DepositEditDate; }
            set { SetPropertyValue<DateTime>("dt_DepositEditDate", ref fdt_DepositEditDate, value); }
        }
        int fn_FlowNum;
        public int n_FlowNum
        {
            get { return fn_FlowNum; }
            set { SetPropertyValue<int>("n_FlowNum", ref fn_FlowNum, value); }
        }
        string fs_Addresses;
        [Size(2000)]
        public string s_Addresses
        {
            get { return fs_Addresses; }
            set { SetPropertyValue<string>("s_Addresses", ref fs_Addresses, value); }
        }
        string fs_ZipCodes;
        [Size(150)]
        public string s_ZipCodes
        {
            get { return fs_ZipCodes; }
            set { SetPropertyValue<string>("s_ZipCodes", ref fs_ZipCodes, value); }
        }
        string fs_ContactsLastName;
        [Size(500)]
        public string s_ContactsLastName
        {
            get { return fs_ContactsLastName; }
            set { SetPropertyValue<string>("s_ContactsLastName", ref fs_ContactsLastName, value); }
        }
        string fs_ContactsFirstName;
        [Size(500)]
        public string s_ContactsFirstName
        {
            get { return fs_ContactsFirstName; }
            set { SetPropertyValue<string>("s_ContactsFirstName", ref fs_ContactsFirstName, value); }
        }
        string fs_ContactsTel;
        [Size(200)]
        public string s_ContactsTel
        {
            get { return fs_ContactsTel; }
            set { SetPropertyValue<string>("s_ContactsTel", ref fs_ContactsTel, value); }
        }
        string fs_ContactsAddresses;
        [Size(4000)]
        public string s_ContactsAddresses
        {
            get { return fs_ContactsAddresses; }
            set { SetPropertyValue<string>("s_ContactsAddresses", ref fs_ContactsAddresses, value); }
        }
        string fs_ContactsZipCode;
        [Size(150)]
        public string s_ContactsZipCode
        {
            get { return fs_ContactsZipCode; }
            set { SetPropertyValue<string>("s_ContactsZipCode", ref fs_ContactsZipCode, value); }
        }
        int fn_FirstContactID;
        public int n_FirstContactID
        {
            get { return fn_FirstContactID; }
            set { SetPropertyValue<int>("n_FirstContactID", ref fn_FirstContactID, value); }
        }
        int fn_PatentCaseCount;
        public int n_PatentCaseCount
        {
            get { return fn_PatentCaseCount; }
            set { SetPropertyValue<int>("n_PatentCaseCount", ref fn_PatentCaseCount, value); }
        }
        int fn_TMCaseCount;
        public int n_TMCaseCount
        {
            get { return fn_TMCaseCount; }
            set { SetPropertyValue<int>("n_TMCaseCount", ref fn_TMCaseCount, value); }
        }
        int fn_CopyrightCaseCount;
        public int n_CopyrightCaseCount
        {
            get { return fn_CopyrightCaseCount; }
            set { SetPropertyValue<int>("n_CopyrightCaseCount", ref fn_CopyrightCaseCount, value); }
        }
        int fn_DomainCaseCount;
        public int n_DomainCaseCount
        {
            get { return fn_DomainCaseCount; }
            set { SetPropertyValue<int>("n_DomainCaseCount", ref fn_DomainCaseCount, value); }
        }
        int fn_OtherCaseCount;
        public int n_OtherCaseCount
        {
            get { return fn_OtherCaseCount; }
            set { SetPropertyValue<int>("n_OtherCaseCount", ref fn_OtherCaseCount, value); }
        }
        string fs_AccountName;
        [Size(200)]
        public string s_AccountName
        {
            get { return fs_AccountName; }
            set { SetPropertyValue<string>("s_AccountName", ref fs_AccountName, value); }
        }
        string fs_BankName;
        [Size(200)]
        public string s_BankName
        {
            get { return fs_BankName; }
            set { SetPropertyValue<string>("s_BankName", ref fs_BankName, value); }
        }
        string fs_AccountNo;
        [Size(200)]
        public string s_AccountNo
        {
            get { return fs_AccountNo; }
            set { SetPropertyValue<string>("s_AccountNo", ref fs_AccountNo, value); }
        }
        string fs_AccountCode;
        [Size(40)]
        public string s_AccountCode
        {
            get { return fs_AccountCode; }
            set { SetPropertyValue<string>("s_AccountCode", ref fs_AccountCode, value); }
        }
        string fs_TaxCode;
        public string s_TaxCode
        {
            get { return fs_TaxCode; }
            set { SetPropertyValue<string>("s_TaxCode", ref fs_TaxCode, value); }
        }
        string fs_RegAddress;
        [Size(400)]
        public string s_RegAddress
        {
            get { return fs_RegAddress; }
            set { SetPropertyValue<string>("s_RegAddress", ref fs_RegAddress, value); }
        }
        string fs_RegTel;
        public string s_RegTel
        {
            get { return fs_RegTel; }
            set { SetPropertyValue<string>("s_RegTel", ref fs_RegTel, value); }
        }
        string fs_InvoiceTo;
        [Size(200)]
        public string s_InvoiceTo
        {
            get { return fs_InvoiceTo; }
            set { SetPropertyValue<string>("s_InvoiceTo", ref fs_InvoiceTo, value); }
        }
        int fn_SecurityLevelID;
        [Indexed(Name = @"in_SecurityLevelID_TCstmr_Client")]
        public int n_SecurityLevelID
        {
            get { return fn_SecurityLevelID; }
            set { SetPropertyValue<int>("n_SecurityLevelID", ref fn_SecurityLevelID, value); }
        }
        int fn_PPreferentialCombineID;
        public int n_PPreferentialCombineID
        {
            get { return fn_PPreferentialCombineID; }
            set { SetPropertyValue<int>("n_PPreferentialCombineID", ref fn_PPreferentialCombineID, value); }
        }
        int fn_TPreferentialCombineID;
        public int n_TPreferentialCombineID
        {
            get { return fn_TPreferentialCombineID; }
            set { SetPropertyValue<int>("n_TPreferentialCombineID", ref fn_TPreferentialCombineID, value); }
        }
        int fn_CPreferentialCombineID;
        public int n_CPreferentialCombineID
        {
            get { return fn_CPreferentialCombineID; }
            set { SetPropertyValue<int>("n_CPreferentialCombineID", ref fn_CPreferentialCombineID, value); }
        }
        int fn_DPreferentialCombineID;
        public int n_DPreferentialCombineID
        {
            get { return fn_DPreferentialCombineID; }
            set { SetPropertyValue<int>("n_DPreferentialCombineID", ref fn_DPreferentialCombineID, value); }
        }
        int fn_OPreferentialCombineID;
        public int n_OPreferentialCombineID
        {
            get { return fn_OPreferentialCombineID; }
            set { SetPropertyValue<int>("n_OPreferentialCombineID", ref fn_OPreferentialCombineID, value); }
        }
        string fs_NotClaimMoney;
        [Size(2)]
        public string s_NotClaimMoney
        {
            get { return fs_NotClaimMoney; }
            set { SetPropertyValue<string>("s_NotClaimMoney", ref fs_NotClaimMoney, value); }
        }
        string fs_FirstClientAddress;
        [Size(1000)]
        public string s_FirstClientAddress
        {
            get { return fs_FirstClientAddress; }
            set { SetPropertyValue<string>("s_FirstClientAddress", ref fs_FirstClientAddress, value); }
        }
        string fs_PriceDesc;
        [Size(SizeAttribute.Unlimited)]
        public string s_PriceDesc
        {
            get { return fs_PriceDesc; }
            set { SetPropertyValue<string>("s_PriceDesc", ref fs_PriceDesc, value); }
        }
        [Association(@"TCstmr_ClientAddressReferencesTCstmr_Client")]
        public XPCollection<TCstmr_ClientAddress> TCstmr_ClientAddresss { get { return GetCollection<TCstmr_ClientAddress>("TCstmr_ClientAddresss"); } }
        [Association(@"TCstmr_ClientChangeHistoryReferencesTCstmr_Client")]
        public XPCollection<TCstmr_ClientChangeHistory> TCstmr_ClientChangeHistorys { get { return GetCollection<TCstmr_ClientChangeHistory>("TCstmr_ClientChangeHistorys"); } }
        [Association(@"TCstmr_ClientContactReferencesTCstmr_Client")]
        public XPCollection<TCstmr_ClientContact> TCstmr_ClientContacts { get { return GetCollection<TCstmr_ClientContact>("TCstmr_ClientContacts"); } }
        [Association(@"TCstmr_ClientFileReferencesTCstmr_Client")]
        public XPCollection<TCstmr_ClientFile> TCstmr_ClientFiles { get { return GetCollection<TCstmr_ClientFile>("TCstmr_ClientFiles"); } }
    }

}
