//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PatentCaseSystem.Module.BusinessObjects.DBIPS4_PA
{

    public partial class TCstmr_ClientContact : XPLiteObject
    {
        int fn_ContactID;
        [Key(true)]
        public int n_ContactID
        {
            get { return fn_ContactID; }
            set { SetPropertyValue<int>("n_ContactID", ref fn_ContactID, value); }
        }
        TCstmr_Client fn_ClientID;
        [Association(@"TCstmr_ClientContactReferencesTCstmr_Client")]
        public TCstmr_Client n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<TCstmr_Client>("n_ClientID", ref fn_ClientID, value); }
        }
        string fs_FirstName;
        public string s_FirstName
        {
            get { return fs_FirstName; }
            set { SetPropertyValue<string>("s_FirstName", ref fs_FirstName, value); }
        }
        string fs_LastName;
        public string s_LastName
        {
            get { return fs_LastName; }
            set { SetPropertyValue<string>("s_LastName", ref fs_LastName, value); }
        }
        string fs_NativeName;
        [Size(200)]
        public string s_NativeName
        {
            get { return fs_NativeName; }
            set { SetPropertyValue<string>("s_NativeName", ref fs_NativeName, value); }
        }
        string fs_OtherName;
        [Size(200)]
        public string s_OtherName
        {
            get { return fs_OtherName; }
            set { SetPropertyValue<string>("s_OtherName", ref fs_OtherName, value); }
        }
        string fs_IPType;
        [Size(50)]
        public string s_IPType
        {
            get { return fs_IPType; }
            set { SetPropertyValue<string>("s_IPType", ref fs_IPType, value); }
        }
        int fn_Language;
        public int n_Language
        {
            get { return fn_Language; }
            set { SetPropertyValue<int>("n_Language", ref fn_Language, value); }
        }
        string fs_JobTitle;
        public string s_JobTitle
        {
            get { return fs_JobTitle; }
            set { SetPropertyValue<string>("s_JobTitle", ref fs_JobTitle, value); }
        }
        string fs_Prefix;
        [Size(30)]
        public string s_Prefix
        {
            get { return fs_Prefix; }
            set { SetPropertyValue<string>("s_Prefix", ref fs_Prefix, value); }
        }
        string fs_Phone;
        [Size(150)]
        public string s_Phone
        {
            get { return fs_Phone; }
            set { SetPropertyValue<string>("s_Phone", ref fs_Phone, value); }
        }
        string fs_Mobile;
        [Size(150)]
        public string s_Mobile
        {
            get { return fs_Mobile; }
            set { SetPropertyValue<string>("s_Mobile", ref fs_Mobile, value); }
        }
        string fs_Fax;
        [Size(150)]
        public string s_Fax
        {
            get { return fs_Fax; }
            set { SetPropertyValue<string>("s_Fax", ref fs_Fax, value); }
        }
        string fs_Email;
        [Size(300)]
        public string s_Email
        {
            get { return fs_Email; }
            set { SetPropertyValue<string>("s_Email", ref fs_Email, value); }
        }
        string fs_Website;
        [Size(300)]
        public string s_Website
        {
            get { return fs_Website; }
            set { SetPropertyValue<string>("s_Website", ref fs_Website, value); }
        }
        string fs_IMAddress;
        public string s_IMAddress
        {
            get { return fs_IMAddress; }
            set { SetPropertyValue<string>("s_IMAddress", ref fs_IMAddress, value); }
        }
        string fs_Facebook;
        [Size(200)]
        public string s_Facebook
        {
            get { return fs_Facebook; }
            set { SetPropertyValue<string>("s_Facebook", ref fs_Facebook, value); }
        }
        string fs_Twitter;
        [Size(200)]
        public string s_Twitter
        {
            get { return fs_Twitter; }
            set { SetPropertyValue<string>("s_Twitter", ref fs_Twitter, value); }
        }
        string fs_PreferContact;
        [Size(10)]
        public string s_PreferContact
        {
            get { return fs_PreferContact; }
            set { SetPropertyValue<string>("s_PreferContact", ref fs_PreferContact, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
        int fn_Sequence;
        public int n_Sequence
        {
            get { return fn_Sequence; }
            set { SetPropertyValue<int>("n_Sequence", ref fn_Sequence, value); }
        }
        DateTime fdt_CreateDate;
        public DateTime dt_CreateDate
        {
            get { return fdt_CreateDate; }
            set { SetPropertyValue<DateTime>("dt_CreateDate", ref fdt_CreateDate, value); }
        }
        DateTime fdt_EditDate;
        public DateTime dt_EditDate
        {
            get { return fdt_EditDate; }
            set { SetPropertyValue<DateTime>("dt_EditDate", ref fdt_EditDate, value); }
        }
        string fs_IPRole;
        [Size(50)]
        public string s_IPRole
        {
            get { return fs_IPRole; }
            set { SetPropertyValue<string>("s_IPRole", ref fs_IPRole, value); }
        }
        string fs_Identity;
        [Size(50)]
        public string s_Identity
        {
            get { return fs_Identity; }
            set { SetPropertyValue<string>("s_Identity", ref fs_Identity, value); }
        }
        [Association(@"TCstmr_ClientConAddressReferencesTCstmr_ClientContact")]
        public XPCollection<TCstmr_ClientConAddress> TCstmr_ClientConAddresss { get { return GetCollection<TCstmr_ClientConAddress>("TCstmr_ClientConAddresss"); } }
    }

}
