//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PatentCaseSystem.Module.BusinessObjects.DBIPS4_PA
{

    public partial class TCstmr_ClientChangeHistory : XPLiteObject
    {
        int fn_ID;
        [Key(true)]
        public int n_ID
        {
            get { return fn_ID; }
            set { SetPropertyValue<int>("n_ID", ref fn_ID, value); }
        }
        TCstmr_Client fn_ClientID;
        [Association(@"TCstmr_ClientChangeHistoryReferencesTCstmr_Client")]
        public TCstmr_Client n_ClientID
        {
            get { return fn_ClientID; }
            set { SetPropertyValue<TCstmr_Client>("n_ClientID", ref fn_ClientID, value); }
        }
        string fs_ChangeProject;
        [Size(50)]
        public string s_ChangeProject
        {
            get { return fs_ChangeProject; }
            set { SetPropertyValue<string>("s_ChangeProject", ref fs_ChangeProject, value); }
        }
        string fs_ChangeFrom;
        [Size(1000)]
        public string s_ChangeFrom
        {
            get { return fs_ChangeFrom; }
            set { SetPropertyValue<string>("s_ChangeFrom", ref fs_ChangeFrom, value); }
        }
        string fs_ChangeTo;
        [Size(1000)]
        public string s_ChangeTo
        {
            get { return fs_ChangeTo; }
            set { SetPropertyValue<string>("s_ChangeTo", ref fs_ChangeTo, value); }
        }
        DateTime fdt_ChangeDate;
        public DateTime dt_ChangeDate
        {
            get { return fdt_ChangeDate; }
            set { SetPropertyValue<DateTime>("dt_ChangeDate", ref fdt_ChangeDate, value); }
        }
        string fs_Notes;
        [Size(800)]
        public string s_Notes
        {
            get { return fs_Notes; }
            set { SetPropertyValue<string>("s_Notes", ref fs_Notes, value); }
        }
    }

}
